os: unstable

platform:
  - x64

install:
  - choco install opencv -version 2.4.9.20140518 

before_build:
  - SET ARCH=x64
  - SET APP_PATH=%CD%
  - IF EXIST C:\OpenCV* CD C:\OpenCV*
  - SET OPENCV_ROOT_PATH=%CD%\opencv
  - CD %APP_PATH%
  - SET OPENCV_DIR=%OPENCV_ROOT_PATH%\build\%ARCH%\vc12
  
build_script:
  - CD build
  - cmake -G "Visual Studio 12 2013 Win64" ../tests
  - msbuild TegroundLib.sln
